services:
  leopard_imaging_tool:
    image: leopard_imaging_tool:ubuntu20
    build:
      context: ../docker/
    container_name: leopard
    environment:
      DISPLAY: ${DISPLAY}
    devices:
      - "/dev/video12:/dev/video12"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME/.Xauthority:/root/.Xauthority"
      - "../:/root/linux_camera_tool"
    privileged: true
    pid: "host"
    network_mode: "host"
    command: sleep infinity
